version: 2.1
orbs:
  node: circleci/node@4.1
jobs:
  build-static-files:
    docker:
      - image: cimg/node:15.1
    working_directory: ~/app
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Build
          command: yarn run build
      - run:
          name: Build Tar
          command:
            - tar czf build.tgz ./build ./Dockerfile
      - save_cache:
          key: build-cache-{{ checksum "build.tgz" }}
          paths:
            - ~/app/build.tgz
  build-push-image:
    machine: true
    working_directory: ~/app
    steps:
      - restore_cache:
          key: build-cache
      - run: tar xzf ~/app/build.tgz && cd build
      - run:
          name: DockerHub Login
          command: docker login -u cwy805435028 -p -Cwyzjgyslj301
      - run:
          name: Build Image
          command: docker build -t cwy805435028/cicd .
      - run:
          name: Push Image
          command: docker push cwy805435028/cicd
workflows:
  Build and Push:
    jobs:
      - build-static-files
      - build-push-image:
          requires:
            - build-static-files
