version: 2.1
orbs:
  node: circleci/node@4.1
working_directory: ~/app
jobs:
  build-static-files:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Build
          command: yarn run build
      - save_cache:
          key: build-cache
          paths:
            - ~/app/build
            - ~/app/Dockerfile
  build-push-image:
    machine: true
    steps:
      - restore_cache:
          key: build-cache
      - run: cd $CIRCLE_WORKING_DIRECTORY
      - run:
          name: DockerHub Login
          command: docker login -u cwy805435028 -p -Cwyzjgyslj301
      - run:
          name: Build Image
          command: docker build -t cwy805435028/cicd .
      - run:
          name: Push Image
          command: docker push cwy805435028/cicd
workflows:
  Build and Push:
    jobs:
      - build-static-files
      - build-push-image:
          requires:
            - build-static-files
