version: 2.1
orbs:
  node: circleci/node@4.1
working_directory: ~/app
jobs:
  build-and-push:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Build
          command: yarn run build
      - run:
        name: DockerHub Login
        command: docker login -u cwy805435028 -p -Cwyzjgyslj301
      - run:
        name: Build Image
        command: docker build -t cwy805435028/cicd
      - run:
        name: Push Image
        command: docker push cwy805435028/cicd

workflows:
  sample:
    jobs:
      - build-and-push
