version: 2.1
orbs:
  node: circleci/node@4.1
  aws-ecr: circleci/aws-ecr@7.0.0
jobs:
  build-static-files:
    docker:
      - image: cimg/node:15.1
    working_directory: ~/app
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Build
          command: yarn run build
      - run:
          name: Build Tar
          command: tar czf build.tgz ./build ./Dockerfile
      - save_cache:
          key: build-cache-{{ checksum "build.tgz" }}
          paths:
            - ~/app/build.tgz
  build-push-image:
    machine: true
    working_directory: ~/app
    steps:
      - restore_cache:
          key: build-cache
      - run: tar xzf ~/app/build.tgz && cd build
      - aws-ecr/build-and-push-image:
          account-url: 636597884343.dkr.ecr.ap-northeast-1.amazonaws.com
          aws-access-key-id: AKIAZIOBQ2W3ZPXRDY5T
          aws-secret-access-key: Yu2GZ9nXnbothXW1MqokyHCarN+Qh0Obt+aJjnQ
          no-output-timeout: 20m
          repo: hello-world
          skip-when-tags-exist: false
          tag: 'latest'
workflows:
  Build and Push:
    jobs:
      - build-static-files
      - build-push-image:
          requires:
            - build-static-files
